keep xcffib to ver 1.5.0 due to 1.6.0 not ok
Exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/xcffib/__init__.py", line 465, in List
    def to_nullsep_string(self) -> list[str]:
TypeError: 'type' object is not subscriptable

Signed-off-by: Huaqi Fang <578567190@qq.com>